version: 2

sources:
  - name: fivetran_raw_data
    database: raw
    tables:
      - name: employees
        description: "One record per employee"
        columns:
          - name: employee_id
            description: "the id of each employee"
          - name: date1
          - name: date2
          - name: team
      - name: employee_info

  - name: fivetran_fivetran_schema1
    database: raw
    tables:
      - name: customer

  - name: fivetran_fivetran_schema2
    database: raw
    tables:
      - name: nation
      - name: region